CREATE TABLE FELHASZNALOK 
(
  NEV VARCHAR2(50) NOT NULL 
, JELSZO VARCHAR2(16) NOT NULL 
, EGYENLEG NUMBER DEFAULT 0 NOT NULL 
, TORZSVASARLO NUMBER DEFAULT 0 NOT NULL 
, LAKCIM VARCHAR2(50 BYTE) NOT NULL 
, VAROS_NEV VARCHAR2(50 BYTE) NOT NULL 
, CONSTRAINT FELHASZNALOK_PK PRIMARY KEY (NEV)
, CONSTRAINT FELHASZNALOK_FK FOREIGN KEY (VAROS_NEV) REFERENCES VAROS(V_NEV)
)

CREATE TABLE ARU 
(
  NEV VARCHAR2(50) NOT NULL 
, KAT_NEV VARCHAR2(50) NOT NULL
, MEGJELENES DATE NOT NULL
, EGYSEG_AR INT NOT NULL
, KESZLET INT NOT NULL
, CONSTRAINT ARU_PK PRIMARY KEY (NEV)
, CONSTRAINT ARU_FK FOREIGN KEY (KAT_NEV) REFERENCES KATEGORIA(KAT_NEV)
)

CREATE TABLE SZALLITAS
(
  V_NEV VARCHAR2(50) NOT NULL
, INIT_DATUM DATE NOT NULL
, FINAL_DATUM DATE NOT NULL
, SZALLITAS_KTG INT NOT NULL
, CONSTRAINT SZALLITAS_FK FOREIGN KEY (V_NEV) REFERENCES VAROS(V_NEV)
)