CREATE TABLE VELEMENY
(
  FELH_NEV VARCHAR2(50) NOT NULL
, ARU_NEV VARCHAR2(50) NOT NULL
, VELEMENY_SZOVEG VARCHAR2(255) NOT NULL
, CONSTRAINT VELEMENY_FK FOREIGN KEY (FELH_NEV) REFERENCES FELHASZNALOK(NEV)
, CONSTRAINT VELEMENY_FK2 FOREIGN KEY (ARU_NEV) REFERENCES ARU(NEV)
)

CREATE TABLE KOSAR
(
  ARU_NEV VARCHAR2(50) NOT NULL
, DARAB_SZAM NUMBER DEFAULT 0 NOT NULL
, CONSTRAINT KOSAR_FK FOREIGN KEY (ARU_NEV) REFERENCES ARU(NEV)
)

CREATE TABLE RENDELESEK
(
  FELH_NEV VARCHAR2(50) NOT NULL
, ARU_NEV VARCHAR2(50) NOT NULL
, EGYSEG_AR INT NOT NULL
, DARAB_SZAM NUMBER NOT NULL
, IDOPONT DATE NOT NULL
, CONSTRAINT RENDELESEK_PK PRIMARY KEY (IDOPONT)
, CONSTRAINT RENDELESEK_FK FOREIGN KEY (FELH_NEV) REFERENCES FELHASZNALOK(NEV)
, CONSTRAINT RENDELESEK_FK2 FOREIGN KEY (ARU_NEV) REFERENCES ARU(NEV)
)