CREATE TABLE SZAMLA
(
  FELH_NEV VARCHAR2(50) NOT NULL
, IDOPONT DATE NOT NULL
, VEGOSSZEG NUMBER DEFAULT 0 NOT NULL
, ISKISZALLITVA NUMBER DEFAULT 0 NOT NULL
, CONSTRAINT SZAMLA_FK FOREIGN KEY (FELH_NEV) REFERENCES FELHASZNALOK(NEV)
, CONSTRAINT SZAMLA_FK2 FOREIGN KEY (IDOPONT) REFERENCES RENDELESEK(IDOPONT)
)